### ISSUE TITLE
-d get wrong resolution

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/hydracastlelabyrinth#13]
Dunno if it bigendian machiens which cause that, or sdl2 on amigaos4, or its general Hydra bug, but, when you run it like: `hcl -d` , it should take the resolution of your current destop and runs with that resolution.

So i have 1920x1080 resolution, and when i do `hcl -d`, it runs instead in the 1080x1920 (so swapped values).  And then as i didn't have that kind of resolution its fallback to 640x480.

Can you check plz it on our side, and if it bug in our SDL2 i can report it ?

**Comment by ptitSeb** [comment]
Oooh, yes, it was indeed inverted in the code O_o

I have fixed that, it should works now.

**Comment by kas1e** [comment]
Yeah, now its write in console "1920x1080", but, it stilld dind'e use that resolution, but fallback to 640x480 by some reassons .. Maybe "scaling" which automatically choicen as "x4" didn't fit into 1920x1080, so fallback to 640x480 ?

**Comment by ptitSeb** [comment]
Mmm, I think there is an issue on amiga side then.

When using "-d" mode in SDL2, I create the windows using `SDL_WINDOW_FULLSCREEN_DESKTOP` flag.
That way, I use current desktop mode, and I'm not supposed to need to set any W or H for the Window (I put 0, 0). I works like that on the Linux machine I tried it on, but maybe it is needed to put actual value for amiga?

**Comment by kas1e** [comment]
Yeah, SDL2 mantainer confirm it is issue on our side, and he will fix it soon. Thanks for help as usual :)

**Comment by ptitSeb** [comment]
Can I close this bug now, it's fixed right?

**Comment by kas1e** [comment]
Its in our SDL2 bugtracker, so of course we can close it , as it on our side.
