### ISSUE TITLE
Problem with saving in linux.

### ISSUE THREAD

**Issue by mxlgv** [ptitSeb/hydracastlelabyrinth#27]
I made a port on KolibriOS and noticed that save.tmp is deleted when I exit. Checked in Linux the same trouble.
I decided not to delete this file and deleted "remove" however after that it started to issue this. Any ideas?

![image](https://user-images.githubusercontent.com/51446645/175657286-087077d9-c48e-49ae-8053-d8f25d3563f3.png)

**Comment by ptitSeb** [comment]
Did you go to a Save point to save in the game? You cannot save everywhere in this game but just at the save point (they are placed before dungeon door).

**Comment by mxlgv** [comment]
With this, I figured it out. Thank you. However, this is not the point. The save file is deleted when you exit the game.

**Comment by ptitSeb** [comment]
Strange, not on my side. I don't have issue with save/load. Do you have any error message on the console maybe?

**Comment by turbocat2001** [comment]
I am using SDL1. Could this be the problem?

**Comment by mxlgv** [comment]
Can you please show this very "dungeon door". Most likely I did not understand correctly.

**Comment by mxlgv** [comment]
For some reason I was sure that the game should be saved in every room. As in the online version, sorry, you can close. False alarm.

**Comment by ptitSeb** [comment]
![image](https://user-images.githubusercontent.com/3250792/175663512-8635b977-7787-457c-bb24-9195f6621ba5.png)

For the record, this is a dungeon door, and the blue losange stuff is a save point.
