### ISSUE TITLE
Flatpak distribution

### ISSUE THREAD

**Issue by fpiesche** [ptitSeb/hydracastlelabyrinth#28]
With the popularity of the Steam Deck I figured it might be worth distributing HCL as a Flatpak!

I've put together a manifest build HCL from the latest versioned tag (if present, or the master branch if not) and wrap it all up nicely in a Flatpak. If this were added to Flathub, Steam Deck users could just get HCL in a playable form using the Discover store like lots of other free apps and games! Similarly any other Linux distribution with Flatpak support would have easy access to the game.

Notably however, for me to submit a PR to Flathub for HCL to be listed there, their [submission guidelines](https://github.com/flathub/flathub/wiki/App-Submission) say that if the Flatpak distribution isn't actually under the direct control of project developers, they should at least be giving permission for their software to be distributed as Flatpak.

Would you be okay with me submitting a PR to Flathub to build HCL for Linux as a Flatpak (once I'm done fixing what's wrong with my build), to make the project easier to access by Linux users?

Do note that this wouldn't involve any additional work from your end at this point - once Flathub has a build manifest, it will automatically monitor the git repositories specified in it (ie. in this case just this one) for new tags and will rebuild the Flatpak on Flathub infrastructure if any source gets a new tag matching a monitoring regex (I've set this up to be semver tags). Maintenance work on the Flathub manifest would be required only if someone makes major changes to how building HCL for Linux works, or the dependencies required.

**Comment by ptitSeb** [comment]
Yeah sure, no problem.

**Comment by fpiesche** [comment]
There we go! Once the PR above gets merged, HCL will be available on Flathub :)

**Comment by ptitSeb** [comment]
Nice :) Thanks!

**Comment by fpiesche** [comment]
Just noticed that saving doesn't work in the Flatpak build, because it tries to save to the `data` directory which is non-persistent. Will put together a patch to write saves to the user's home directory on desktop SDL builds over the next couple of days.

**Comment by duskull88** [comment]
> Just noticed that saving doesn't work in the Flatpak build, because it tries to save to the `data` directory which is non-persistent. Will put together a patch to write saves to the user's home directory on desktop SDL builds over the next couple of days.

Please do that, I made good progress in the game but I experienced a crash and then I learned that my save was gone. And thanks for the flatpak build!

**Comment by fpiesche** [comment]
> Please do that, I made good progress in the game but I experienced a crash and then I learned that my save was gone. And thanks for the flatpak build!

Now done :)
