### ISSUE TITLE
morphos build

### ISSUE THREAD

**Issue by BeWorld2018** [ptitSeb/hydracastlelabyrinth#5]
Hi
I's possible to pull request for MorphOS build (SDL 1.2) ?
I compile for MorphOS with your AmigaOS changes
Thanks
BeWorld

**Comment by ptitSeb** [comment]
Sure, as long as it specific code is guarded by `#ifdef` and it still build on other platform, that will be great to have!

**Comment by BeWorld2018** [comment]
Ok, je viens de faire des "Pull Requests"
Merci !

**Comment by ptitSeb** [comment]
C'est bon, j'ai tout validé.

**Comment by BeWorld2018** [comment]
Ok j'ai compilé avec succes, je fais une sortie sur morphos-storage.net
Merci encore pour la version AmigaOS qui a permis la version MorphOS.

**Comment by ptitSeb** [comment]
Cool, merci pour le port MorphOS :)
